# Generated by Django 3.0.6 on 2020-06-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_param', models.CharField(blank=True, max_length=255, null=True)),
                ('date_proc_streng', models.DateField(blank=True, null=True)),
                ('depth_coating', models.FloatField(blank=True, null=True)),
                ('roughness', models.FloatField(blank=True, null=True)),
                ('hardness_coating', models.FloatField(blank=True, null=True)),
                ('struct_coating', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_hardness', models.FloatField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample',
            },
        ),
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_material',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sample_type',
            },
        ),
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_particle', models.IntegerField(blank=True, null=True)),
                ('speed_collision', models.IntegerField(blank=True, null=True)),
                ('add_param', models.CharField(blank=True, max_length=255, null=True)),
                ('corner_collision', models.IntegerField(blank=True, null=True)),
                ('date_trials', models.DateField(blank=True, null=True)),
                ('date_end_trials', models.DateField(blank=True, null=True)),
                ('type_particle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='Sample.Sample')),
            ],
            options={
                'db_table': 'trials',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Sample.SampleMaterial'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='Sample.SampleType'),
        ),
        migrations.CreateModel(
            name='ReceivedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_weight', models.FloatField(blank=True, null=True)),
                ('time_trials', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=None)),
                ('trials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trials_values', to='Sample.Trials')),
            ],
            options={
                'db_table': 'received_values',
            },
        ),
    ]
