# Generated by Django 3.0.6 on 2020-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_param', models.CharField(blank=True, max_length=255, null=True)),
                ('date_proc_streng', models.DateField(blank=True, null=True)),
                ('depth_coating', models.FloatField(blank=True, null=True)),
                ('roughness', models.FloatField(blank=True, null=True)),
                ('hardness_coating', models.FloatField(blank=True, null=True)),
                ('struct_coating', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sample_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleMaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(blank=True, max_length=255, null=True)),
                ('gost', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sample_material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sample_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_particle', models.IntegerField(blank=True, null=True)),
                ('speed_collision', models.IntegerField(blank=True, null=True)),
                ('add_param', models.CharField(blank=True, max_length=255, null=True)),
                ('corner_collision', models.IntegerField(blank=True, null=True)),
                ('date_trials', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trials',
                'managed': False,
            },
        ),
    ]
