# Generated by Django 3.0.6 on 2020-06-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_weight', models.FloatField(blank=True, null=True)),
                ('time_trials', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('trials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='Sample.Trials')),
            ],
        ),
        migrations.DeleteModel(
            name='SampleMaterialType',
        ),
    ]
