# Generated by Django 3.0.6 on 2020-06-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0002_auto_20200616_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplematerial',
            options={'ordering': ['name', 'type']},
        ),
    ]
