# Generated by Django 3.0.6 on 2020-06-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0002_auto_20200601_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedvalues',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
