# Generated by Django 3.0.6 on 2020-06-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0003_auto_20200601_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedvalues',
            name='trials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials_values', to='Sample.Trials'),
        ),
    ]
