# Generated by Django 3.0.6 on 2020-06-21 15:00

import Sample.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0003_auto_20200617_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedvalues',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=Sample.models.ReceivedValues.experement_image_path),
        ),
    ]
