# Generated by Django 3.0.6 on 2020-06-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0004_auto_20200601_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedvalues',
            options={'managed': False},
        ),
    ]
