# Generated by Django 3.0.6 on 2020-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0004_auto_20200621_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
