# Generated by Django 3.0.6 on 2020-06-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0006_auto_20200628_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trials',
            name='author',
        ),
        migrations.RemoveField(
            model_name='trials',
            name='sample',
        ),
        migrations.DeleteModel(
            name='ReceivedValues',
        ),
        migrations.DeleteModel(
            name='Trials',
        ),
    ]
