# Generated by Django 3.0.6 on 2020-06-28 20:29

import Trial.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sample', '0007_auto_20200628_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size_particle', models.IntegerField(blank=True, null=True, verbose_name='Размер частиц')),
                ('speed_collision', models.IntegerField(blank=True, null=True, verbose_name='Скорость соударения')),
                ('add_param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные параметры частицы')),
                ('corner_collision', models.IntegerField(blank=True, null=True, verbose_name='Угол соударения ')),
                ('date_trials', models.DateField(blank=True, null=True, verbose_name='Дата проведения испытания')),
                ('date_end_trials', models.DateField(blank=True, null=True, verbose_name='Время окончания испытания')),
                ('type_particle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип частицы')),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='Sample.Sample')),
            ],
            options={
                'db_table': 'trials',
            },
        ),
        migrations.CreateModel(
            name='ReceivedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('change_weight', models.FloatField(default=0, verbose_name='Масса образца после эксперимента')),
                ('time_trials', models.IntegerField(default=0, verbose_name='Длительность эксперимента')),
                ('image', models.FileField(blank=True, null=True, upload_to=Trial.models.ReceivedValues.experement_image_path, verbose_name='Изображение образца после эксперимента')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trials_values', to='Trial.Trials')),
            ],
            options={
                'db_table': 'received_values',
            },
        ),
    ]
