# Generated by Django 3.0.6 on 2020-07-25 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trials',
            name='abrasive_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расход абразива'),
        ),
        migrations.AddField(
            model_name='trials',
            name='abrasive_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип абразива'),
        ),
        migrations.AddField(
            model_name='trials',
            name='air_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расход воздуха'),
        ),
        migrations.AddField(
            model_name='trials',
            name='chamber_pressure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Давление в камере'),
        ),
        migrations.AddField(
            model_name='trials',
            name='distance_sub',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расстояние от сопла до образца'),
        ),
        migrations.AddField(
            model_name='trials',
            name='flow_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип потока'),
        ),
        migrations.AddField(
            model_name='trials',
            name='nozzle_diam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диаметр сопла'),
        ),
        migrations.AddField(
            model_name='trials',
            name='sample_temp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Температура образца'),
        ),
        migrations.AlterField(
            model_name='receivedvalues',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='receivedvalues',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='trials',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='trials',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='trials',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
