# Generated by Django 3.0.6 on 2020-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trial', '0002_auto_20200725_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedvalues',
            name='droplets_distance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расстояние между каплями'),
        ),
        migrations.AddField(
            model_name='receivedvalues',
            name='number_of_droplet_flow',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Число потоков капель'),
        ),
        migrations.AddField(
            model_name='receivedvalues',
            name='sample_density',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Плотность материала образца'),
        ),
        migrations.AddField(
            model_name='receivedvalues',
            name='sample_erosion_height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Средняя высота зоны эрозийного износа'),
        ),
        migrations.AddField(
            model_name='receivedvalues',
            name='samples_distance_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диаметр крепления образцов на штанге'),
        ),
        migrations.AddField(
            model_name='receivedvalues',
            name='water_density',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Плотность воды'),
        ),
        migrations.AlterField(
            model_name='receivedvalues',
            name='time_trials',
            field=models.FloatField(default=0, verbose_name='Длительность эксперимента'),
        ),
    ]
