# Generated by Django 3.0.6 on 2020-08-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trial', '0003_auto_20200811_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedvalues',
            name='droplets_distance',
        ),
        migrations.RemoveField(
            model_name='receivedvalues',
            name='number_of_droplet_flow',
        ),
        migrations.RemoveField(
            model_name='receivedvalues',
            name='sample_density',
        ),
        migrations.RemoveField(
            model_name='receivedvalues',
            name='sample_erosion_height',
        ),
        migrations.RemoveField(
            model_name='receivedvalues',
            name='samples_distance_diameter',
        ),
        migrations.RemoveField(
            model_name='receivedvalues',
            name='water_density',
        ),
        migrations.AddField(
            model_name='trials',
            name='droplets_distance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расстояние между каплями'),
        ),
        migrations.AddField(
            model_name='trials',
            name='number_of_droplet_flow',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Число потоков капель'),
        ),
        migrations.AddField(
            model_name='trials',
            name='sample_density',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Плотность материала образца'),
        ),
        migrations.AddField(
            model_name='trials',
            name='sample_erosion_height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Средняя высота зоны эрозийного износа'),
        ),
        migrations.AddField(
            model_name='trials',
            name='samples_distance_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диаметр крепления образцов на штанге'),
        ),
        migrations.AddField(
            model_name='trials',
            name='water_density',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Плотность воды'),
        ),
        migrations.CreateModel(
            name='ReceivedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('incubation_period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность инкубационного периода')),
                ('max_erosion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальная скорость эрозии')),
                ('established_erosion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Установившейся скорость эрозии')),
                ('point_max_erosion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общая точка максимальной скорости эрозии')),
                ('point_erosion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общая точка установившейся скорости эрозии')),
                ('type_graph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип графика')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('trials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trial.Trials')),
            ],
            options={
                'db_table': 'received_data',
            },
        ),
    ]
