# Generated by Django 3.0.6 on 2020-07-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Способ упрочнения')),
                ('exp_param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметры упрочнения')),
                ('depth_coating', models.FloatField(blank=True, null=True, verbose_name='Толщина упрочнения')),
                ('hardness_coating', models.FloatField(blank=True, null=True, verbose_name='Твердость упрочнения')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация, которая провела упрочнение')),
                ('struct_coating', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав покрытия')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'db_table': 'modification',
            },
        ),
    ]
